// 模拟的表格数据
export const storeData = {
    "code":0,
    "data":[
      {
          "petID":"001",
          "specie":"柯基",
          "color":"white",
          "born":"2020-08-16",
          "age":2,
          "weight":3,
          "health":"良好",
          "price":489,
          "storeNum":1
      },
      {
        "petID":"002",
        "specie":"萨摩耶",
        "color":"white",
        "born":"2021-03-22",
        "age":1,
        "weight":5,
        "health":"良好",
        "price":1389,
        "storeNum":1
      },
      {
        "petID":"003",
        "specie":"波斯猫",
        "color":"white",
        "born":"2020-10-03",
        "age":2,
        "weight":1.5,
        "health":"良好",
        "price":3599,
        "storeNum":1
      },
      {
        "petID":"004",
        "specie":"金毛犬",
        "color":"white",
        "born":"2020-03-15",
        "age":2,
        "weight":9,
        "health":"良好",
        "price":2799,
        "storeNum":1
      },
      {
        "petID":"005",
        "specie":"加菲猫",
        "color":"white",
        "born":"2021-06-04",
        "age":1,
        "weight":2,
        "health":"良好",
        "price":1389,
        "storeNum":1
      },
      {
        "petID":"006",
        "specie":"布偶猫",
        "color":"white",
        "born":"2021-05-16",
        "age":1,
        "weight":2,
        "health":"良好",
        "price":4299,
        "storeNum":1
      },
    ]
};
